# Run muuktest executor CI with github actions
name: muuktest_v1

# Controls when the workflow will run
on: [push]

env:
    GRADLE_OPTS: '-Xmx1024m -XX:MaxMetaspaceSize=256m'
    GRADLE_USER_HOME: '.gradle-home'
    DIR: './executor'
    DISPLAY: ':99'

jobs:
  build:
  
    runs-on: ubuntu-20.04
    container: muuk/muuktest_v1:0.1
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure executor
        run: |
            Xvfb :99 -screen 0 1366x768x16 &
            ps -ef | grep Xvfb
            if [ ! -d "$DIR" ]; then
              git clone https://github.com/muuklabs/executor.git
            fi
            cd executor/
            git checkout videoEnabled
            printf ${{ vars.MUUKTEST_KEY }} > key.pub
            cat key.pub
            chmod 755 gradlew
            chmod 755 key.pub
            sed -i 's/79.0.3945.36/86.0.4240.22/g' build.gradle
            sed -i 's/0.23.0/0.27.0/g' build.gradle
            cat build.gradle

      - name: Execute test
        run: |
            cd executor/
            python3.7  mkcli.py -p ${{ vars.PROPERTY }} -t ${{ vars.TAG }} -browser chrome


      - name: Print test results
        run: |
            cd executor/
            cat build/test-results/*/T*
